# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.
#
#development:
#  admin_name: First User
#  admin_email: user@example.com
#  admin_password: changeme
#  domain_name: example.com
#  secret_key_base: 374f8eb5cac1d07b347cbe7ef81beea8b9027b88c9f2ac4435266983a993cb54b9f597c4d7ff9c6c93427de4a13a53b5576274050c0145ba614ab610e608124a
#
#test:
#  domain_name: example.com
#  secret_key_base: 7a05a00dea8f6b48ede4c6aece955ca36749be17be678797e8aeda1c471dba6e32b4ca2f4e9245905c1c1f70098ee97261bf6b69d451f60b3cef56bad3c25898
#
## Do not keep production secrets in the repository,
## instead read values from the environment.
#production:
#  admin_name: <%= ENV["ADMIN_NAME"] %>
#  admin_email: <%= ENV["ADMIN_EMAIL"] %>
#  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
#  domain_name: <%= ENV["DOMAIN_NAME"] %>
#  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>


development:
admin_name: First User
admin_email: user@example.com
admin_password: changeme
admin_phone: 8451843028
email_provider_username: <%= ENV["GMAIL_USERNAME"] %>
email_provider_password: <%= ENV["GMAIL_PASSWORD"] %>
domain_name: example.com
secret_key_base: a5c20c937aa729298410b9517c48a8aae13ec271e8ea7a5a9e2d3925cb345c3c148cc51528ebff901686729fc29d89125cf3e3c4d05b60a4e1745c4298b92fe8
test:
domain_name: example.com
secret_key_base: 3298f76c4c4aed6f3660c77bb9b6d8ad250c35285762bdea46d588dd7c1f1edb5b6aada47228b032198490fcc89894b5a5842e5868b5774a4227836c92461b40
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
admin_name: <%= ENV["ADMIN_NAME"] %>
admin_email: <%= ENV["ADMIN_EMAIL"] %>
admin_phone: <%= ENV["ADMIN_PHONE"] %>
admin_password: <%= ENV["ADMIN_PASSWORD"] %>
email_provider_username: <%= ENV["GMAIL_USERNAME"] %>
email_provider_password: <%= ENV["GMAIL_PASSWORD"] %>
domain_name: <%= ENV["DOMAIN_NAME"] %>
secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>